<?php
/**
 * Created by JetBrains PhpStorm.
 * User: gordon
 * Date: 30.03.13
 * Time: 16:32
 * To change this template use File | Settings | File Templates.
 */
?>
<?php
$_recentPosts = $this->getRecentPosts();
$_recentComments = $this->getRecentComments();
$_categories = $this->getCategories();
$_helper = Mage::helper('blog/post');
?>
<div class="block block-blog" title="<?php echo $_helper->__('Blog') ?>">
    <div class="block-title">
        <strong><span><?php echo $_helper->__('Blog') ?></span></strong>
    </div>
    <div class="block-content">
        <p class="block-subtitle"><?php echo $_helper->__('Recent Posts') ?></p>
        <ul id="post-list">
        <?php foreach($_recentPosts as $_post): ?>
            <li><a title="<?php echo $_post->getTitle() ?>" href="<?php echo $_post->getPostUrl() ?>"><?php echo $_post->getTitle() ?></a></li>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateList('post-list');</script>
        <p class="block-subtitle"><?php echo $_helper->__('Recent Comments') ?></p>
        <ul id="post-list">
            <?php foreach($_recentComments as $_comment): ?>
            <li>
                <a rel="external nofollow" href="<?php echo $_comment->getAuthorUrl() ?>"><?php echo $_comment->getAuthorName() ?></a>
                <?php echo $_helper->__('on') ?>
                <a href="<?php echo $_comment->getCommentUrl() ?>"><?php echo $_comment->getPostTitle() ?></a>
            </li>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateList('post-list');</script>
        <p class="block-subtitle"><?php echo $_helper->__('Categories') ?></p>
        <ul id="category-list">
            <?php foreach($_categories as $_category): ?>
            <li><a title="<?php echo $_category->getTitle() ?>" href="<?php echo $_category->getCategoryUrl() ?>"><?php echo $_category->getTitle() ?></a></li>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateList('category-list');</script>
    </div>
</div>