<?php
/**
 * Created by JetBrains PhpStorm.
 * User: gordon
 * Date: 27.03.13
 * Time: 15:04
 * To change this template use File | Settings | File Templates.
 */
?>
<?php
$_postCollection = $this->getLoadedPostCollection();
$_category = $this->getCategory();
$_helper = Mage::helper('blog');
$_authorHelper = Mage::helper('blog/author');
$_commentHelper = Mage::helper('blog/post_comment');
?>
<div class="page-title blog-category-title">
    <h1><?php echo $_category->getTitle() ?></h1>
</div>
<?php foreach($_postCollection as $_post): ?>
    <article id="post-<?php echo $_post->getId() ?>" class="blog-post-excerpt">
        <header class="blog-entry-header">
            <h1 class="blog-entry-title">
                <a rel="bookmark" title="<?php echo $_helper->__('Permanentlink to') . ' ' . $_post->getTitle() ?>" href="<?php echo $_post->getPostUrl() ?>"><?php echo $_post->getTitle() ?></a>
            </h1>
            <?php if($_post->getCommentCount()): ?>
                <div class="comments-link">
                    <a title="Comment on <?php echo $_post->getTitle()?>" href="<?php echo $_post->getPostUrl(array('comment')) ?>">
                        <?php echo $_post->getCommentCount() ?> <?php echo $_post->getCommentCount() == 1 ? $_helper->__('Reply') : $_helper->__('Replies') ?>
                    </a>
                </div>
            <?php elseif($_commentHelper->getIsCustomerAllowedToWrite($_post)): ?>
                <div class="blog-comments-link">
                    <a title="<?php echo $_helper->__('Comment on')?> <?php echo $_post->getTitle() ?>" href="<?php echo $_post->getPostUrl(array('response')) ?>">
                        <?php echo $_helper->__('Leave a reply') ?>
                    </a>
                </div>
            <?php endif; ?>
        </header>
        <div class="blog-entry-content">
            <?php echo $_post->excerptHtml(); ?>
            <?php if($_post->needReadMore()): ?>
                <a class="blog-more-link" href="<?php echo $_post->getPostUrl(array('more')) ?>"><?php echo $_helper->__('Continue reading') ?> <span class="blog-meta-nav">&rarr;</span></a>
            <?php endif; ?>
        </div>
        <footer class="blog-entry-meta">
            <?php echo $_helper->__('This entry was posted') ?>
            <?php $_categoryCollection = $_post->getCategoryCollection() ?>
            <?php if($_categoryCollection->count()): ?>
                <?php echo $_helper->__(' in ') ?>
                <?php foreach($_categoryCollection as $_postCategory): ?>
                    <a rel="category" title="<?php echo $_helper->__('View all posts in') . ' ' . $_postCategory->getTitle() ?>" href="<?php echo $_postCategory->getCategoryUrl() ?>"><?php echo $_postCategory->getTitle() ?></a>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php echo $_helper->__('on') ?>
            <a rel="bookmark" href="<?php echo $_post->getPostUrl() ?>"><?php echo date("D, j M, Y", strtotime($_post->getCreationTime())) ?></a>
            <span class="by-author">
                <?php echo $_helper->__('by') ?>
                <span class="author">
                    <a rel="author" title="<?php echo $_helper->__('View all posts by') . ' ' . $_post->getUsername() ?>" href="<?php echo $_authorHelper->getAuthorUrl($_post->getAuthorId()) ?>"><?php echo $_post->getUsername() ?></a>
                </span>
            </span>
        </footer>
    </article>
<?php endforeach; ?>