<?php
/**
 * Created by JetBrains PhpStorm.
 * User: gordon
 * Date: 27.03.13
 * Time: 15:04
 * To change this template use File | Settings | File Templates.
 */
?>
<?php
$_postCollection = $this->getLoadedPostCollection();
$_category = $this->getCategory();
$_helper = Mage::helper('blog');
?>
<div class="page-title blog-category-title">
    <h1><?php echo $_category->getTitle() ?></h1>
</div>
<?php foreach($_postCollection as $_post): ?>
    <article id="post-<?php echo $_post->getId() ?>" class="blog-post-excerpt">
        <header class="blog-entry-header">
            <h1 class="blog-entry-title">
                <a rel="bookmark" title="<?php echo $_helper->__('Permanentlink to') . ' ' . $_post->getTitle() ?>" href="<?php echo $_post->getPostUrl() ?>"><?php echo $_post->getTitle() ?></a>
            </h1>
        </header>
        <div class="blog-entry-content">
            <?php echo $_post->excerptHtml(); ?>
            <?php if($_post->needReadMore()): ?>
                <a class="blog-more-link" href="<?php echo $_post->getPostUrl(array('more')) ?>"><?php echo $_helper->__('Read more') ?> <span class="blog-meta-nav">&rarr;</span></a>
            <?php endif; ?>
        </div>
        <footer class="blog-entry-meta">
        </footer>
    </article>
<?php endforeach; ?>