<?php
/**
 * Created by JetBrains PhpStorm.
 * User: gordon
 * Date: 28.03.13
 * Time: 13:50
 * To change this template use File | Settings | File Templates.
 */
?>
<?php
$_post = $this->getPost();
$_helper = Mage::helper('blog');
$_authorHelper = Mage::helper('blog/author');
$_commentHelper = Mage::helper('blog/post_comment');
?>
<article id="post-<?php echo $_post->getId() ?>" class="blog-post-view">
    <header class="blog-entry-header page-title blog-post-title">
        <h1><?php echo $_post->getTitle() ?></h1>
        <?php if($_post->getCommentCount()): ?>
            <div class="blog-comments-link">
                <a title="<?php echo $_helper->__('Comment on')?> <?php echo $_post->getTitle() ?>" href="<?php echo $_post->getPostUrl(array('comment')) ?>">
                    <?php echo $_post->getCommentCount() ?> <?php echo $_post->getCommentCount() == 1 ? $_helper->__('Reply') : $_helper->__('Replies') ?>
                </a>
            </div>
        <?php elseif($_commentHelper->getIsCustomerAllowedToWrite($_post)): ?>
            <div class="blog-comments-link">
                <a title="<?php echo $_helper->__('Comment on')?> <?php echo $_post->getTitle() ?>" href="<?php echo $_post->getPostUrl(array('response')) ?>">
                    <?php echo $_helper->__('Leave a reply') ?>
                </a>
            </div>
        <?php endif; ?>
    </header>
    <div class="blog-entry-content">
        <?php echo $_post->contentHtml() ?>
    </div>
    <footer class="blog-entry-meta">
        <?php echo $_helper->__('This entry was posted') ?>
        <?php $_categoryCollection = $_post->getCategoryCollection() ?>
        <?php if($_categoryCollection->count()): ?>
            <?php echo $_helper->__(' in ') ?>
            <?php foreach($_categoryCollection as $_postCategory): ?>
                <a rel="category" title="<?php echo $_helper->__('View all posts in') . ' ' . $_postCategory->getTitle() ?>" href="<?php echo $_postCategory->getCategoryUrl() ?>"><?php echo $_postCategory->getTitle() ?></a>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php $_tagCollection = $_post->getTagCollection() ?>
        <?php if($_tagCollection->count()): ?>
            <?php echo $_helper->__(' tagged ') ?>
            <?php foreach($_tagCollection as $_postTag): ?>
                <a rel="tag" href="<?php echo $_postTag->getTagUrl() ?>"><?php echo $_postTag->getTitle() ?></a>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php echo $_helper->__('on') ?>
        <a rel="bookmark" href="<?php echo $_post->getPostUrl() ?>"><?php echo $_helper->formatDate($_post->getCreationTime(), Zend_Date::DATE_LONG) ?></a>
            <span class="by-author">
                <?php echo $_helper->__('by') ?>
                <span class="author">
                    <a rel="author" title="<?php echo $_helper->__('View all posts by') . ' ' . $_post->getAuthorName() ?>" href="<?php echo $_authorHelper->getAuthorUrl($_post->getAuthorName()) ?>"><?php echo $_post->getAuthorName() ?></a>
                </span>
            </span>
    </footer>
</article>
<?php echo $this->getChildHtml('comment') ?>